### ISSUE TITLE
HA 2025.6 Govee Lan Control failed

### ISSUE THREAD

**Issue by mirceadb7** [wez/govee-lan-hass#71]
After updating to Home Assistant 2025.6 I get an error failed to setup the integration. 

Logger: homeassistant.config_entries
Source: config_entries.py:749
First occurred: 00:34:49 (4 occurrences)
Last logged: 00:42:07

Error setting up entry govee_lan for govee_lan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/govee_lan/__init__.py", line 33, in async_setup_entry
    hass.config_entries.async_forward_entry_setup(entry, component)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?

**Comment by Eric2XU** [comment]
Same issue, now I wish I didnt upgrade HA… I really dont want to spend the time to get the MQTT thing working. Any chance this is a quick fix?

**Comment by hdprice** [comment]
This just broke for me too

**Comment by Eric2XU** [comment]
I fixed it and submitted a PR

PR: #72 

Direct copy of the file for manual replacement: https://github.com/wez/govee-lan-hass/blob/c01de8016eb6a3c6a6e36e70dbc333cadb16521f/custom_components/govee_lan/__init__.py 

He said he’s not updating this repo anymore but at worst take my version of the file and edit your local copy. Since there wont be another update, it shouldn’t get replaced. 

Problem:After upgrading to Home Assistant 2025.5, the integration failed with an error:ModuleNotFoundError: No module named 'custom_components.govee_lan.l'. This was caused by using the outdated async_forward_entry_setup method inside a loop, which led to misinterpreting platform names (e.g., "l" instead of "light").

Solution:

Updated API Call: Replaced async_forward_entry_setup with the new async_forward_entry_setups method.

Simplified Setup: Removed the loop over platforms and now forward all platforms at once:

await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)

This change aligns the integration with the updated Home Assistant architecture and resolves the module import error.

**Comment by rustyk123** [comment]
> I fixed it and submitted a PR
> 
> [#72](https://github.com/wez/govee-lan-hass/pull/72)
> 
> He said he’s not updating this repo anymore but at worst take my version of the file and edit your local copy. Since there wont be another update, it shouldn’t get replaced.
> 
> Problem:After upgrading to Home Assistant 2025.5, the integration failed with an error:ModuleNotFoundError: No module named 'custom_components.govee_lan.l'. This was caused by using the outdated async_forward_entry_setup method inside a loop, which led to misinterpreting platform names (e.g., "l" instead of "light").
> 
> Solution:
> 
> Updated API Call: Replaced async_forward_entry_setup with the new async_forward_entry_setups method.
> 
> Simplified Setup: Removed the loop over platforms and now forward all platforms at once:
> 
> await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
> 
> This change aligns the integration with the updated Home Assistant architecture and resolves the module import error.

Thanks I came here because it stopped working after the 2025.6 update, this worked perfectly!

**Comment by hdprice** [comment]
> > I fixed it and submitted a PR
> > [#72](https://github.com/wez/govee-lan-hass/pull/72)
> > He said he’s not updating this repo anymore but at worst take my version of the file and edit your local copy. Since there wont be another update, it shouldn’t get replaced.
> > Problem:After upgrading to Home Assistant 2025.5, the integration failed with an error:ModuleNotFoundError: No module named 'custom_components.govee_lan.l'. This was caused by using the outdated async_forward_entry_setup method inside a loop, which led to misinterpreting platform names (e.g., "l" instead of "light").
> > Solution:
> > Updated API Call: Replaced async_forward_entry_setup with the new async_forward_entry_setups method.
> > Simplified Setup: Removed the loop over platforms and now forward all platforms at once:
> > await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
> > This change aligns the integration with the updated Home Assistant architecture and resolves the module import error.
> 
> Thanks I came here because it stopped working after the 2025.6 update, this worked perfectly!

I replaced my __init__.py with the one you published but the integration is still not loading for me. I've tried restarting Home Assistant and rebooting the host. 

I'm seeing this in the logs

Logger: homeassistant.util.loop
Source: util/loop.py:77
First occurred: 10:05:43 PM (4 occurrences)
Last logged: 10:05:48 PM

Detected blocking call to import_module with args ('custom_components.govee_lan',) in /usr/src/homeassistant/homeassistant/loader.py, line 1053: ComponentProtocol, importlib.import_module(self.pkg_path) inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 227, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 213, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 154, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.13/asyncio/base_events.py", line 706, in run_until_complete self.run_forever() File "/usr/local/lib/python3.13/asyncio/base_events.py", line 677, in run_forever self._run_once() File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2034, in _run_once handle._run() File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/setup.py", line 171, in async_setup_component result = await _async_setup_component(hass, domain, config) File "/usr/src/homeassistant/homeassistant/setup.py", line 344, in _async_setup_component component = await integration.async_get_component() File "/usr/src/homeassistant/homeassistant/loader.py", line 1005, in async_get_component comp = self._get_component() File "/usr/src/homeassistant/homeassistant/loader.py", line 1053, in _get_component ComponentProtocol, importlib.import_module(self.pkg_path)
Detected blocking call to load_verify_locations with args (<ssl.SSLContext object at 0x7f2a064d3800>, '/usr/local/lib/python3.13/site-packages/certifi/cacert.pem', None, None) in /usr/local/lib/python3.13/ssl.py, line 717: context.load_verify_locations(cafile, capath, cadata) inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_verify_locations Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 227, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 213, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 154, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.13/asyncio/base_events.py", line 706, in run_until_complete self.run_forever() File "/usr/local/lib/python3.13/asyncio/base_events.py", line 677, in run_forever self._run_once() File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2034, in _run_once handle._run() File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run self._context.run(self._callback, *self._args) File "/usr/local/lib/python3.13/site-packages/aiokevoplus/__init__.py", line 482, in __websocket_connect snonce = await self.__get_server_nonce() File "/usr/local/lib/python3.13/site-packages/aiokevoplus/__init__.py", line 159, in __get_server_nonce client = httpx.AsyncClient() File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1402, in __init__ self._transport = self._init_transport( File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1445, in _init_transport return AsyncHTTPTransport( File "/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py", line 297, in __init__ ssl_context = create_ssl_context(verify=verify, cert=cert, trust_env=trust_env) File "/usr/local/lib/python3.13/site-packages/httpx/_config.py", line 40, in create_ssl_context ctx = ssl.create_default_context(cafile=certifi.where()) File "/usr/local/lib/python3.13/ssl.py", line 717, in create_default_context context.load_verify_locations(cafile, capath, cadata)
Detected blocking call to load_default_certs with args (<ssl.SSLContext object at 0x7f29f67d1760>, <Purpose.SERVER_AUTH: _ASN1Object(nid=129, shortname='serverAuth', longname='TLS Web Server Authentication', oid='1.3.6.1.5.5.7.3.1')>) in /usr/local/lib/python3.13/ssl.py, line 722: context.load_default_certs(purpose) inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_default_certs Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 227, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 213, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 154, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.13/asyncio/base_events.py", line 706, in run_until_complete self.run_forever() File "/usr/local/lib/python3.13/asyncio/base_events.py", line 677, in run_forever self._run_once() File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2034, in _run_once handle._run() File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run self._context.run(self._callback, *self._args) File "/usr/local/lib/python3.13/site-packages/aiokevoplus/__init__.py", line 496, in __websocket_connect async for websocket in websockets.connect( File "/usr/local/lib/python3.13/site-packages/websockets/asyncio/client.py", line 603, in __aiter__ async with self as protocol: File "/usr/local/lib/python3.13/site-packages/websockets/asyncio/client.py", line 587, in __aenter__ return await self File "/usr/local/lib/python3.13/site-packages/websockets/asyncio/client.py", line 541, in __await_impl__ self.connection = await self.create_connection() File "/usr/local/lib/python3.13/site-packages/websockets/asyncio/client.py", line 467, in create_connection _, connection = await loop.create_connection(factory, **kwargs) File "/usr/local/lib/python3.13/asyncio/base_events.py", line 1187, in create_connection transport, protocol = await self._create_connection_transport( File "/usr/local/lib/python3.13/asyncio/base_events.py", line 1211, in _create_connection_transport transport = self._make_ssl_transport( File "/usr/local/lib/python3.13/asyncio/selector_events.py", line 83, in _make_ssl_transport ssl_protocol = sslproto.SSLProtocol( File "/usr/local/lib/python3.13/asyncio/sslproto.py", line 295, in __init__ sslcontext = _create_transport_context( File "/usr/local/lib/python3.13/asyncio/sslproto.py", line 55, in _create_transport_context sslcontext = ssl.create_default_context() File "/usr/local/lib/python3.13/ssl.py", line 722, in create_default_context context.load_default_certs(purpose)
Detected blocking call to set_default_verify_paths with args (<ssl.SSLContext object at 0x7f29f67d1760>,) in /usr/local/lib/python3.13/ssl.py, line 534: self.set_default_verify_paths() inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#set_default_verify_paths Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 227, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 213, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 154, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.13/asyncio/base_events.py", line 706, in run_until_complete self.run_forever() File "/usr/local/lib/python3.13/asyncio/base_events.py", line 677, in run_forever self._run_once() File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2034, in _run_once handle._run() File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run self._context.run(self._callback, *self._args) File "/usr/local/lib/python3.13/site-packages/aiokevoplus/__init__.py", line 496, in __websocket_connect async for websocket in websockets.connect( File "/usr/local/lib/python3.13/site-packages/websockets/asyncio/client.py", line 603, in __aiter__ async with self as protocol: File "/usr/local/lib/python3.13/site-packages/websockets/asyncio/client.py", line 587, in __aenter__ return await self File "/usr/local/lib/python3.13/site-packages/websockets/asyncio/client.py", line 541, in __await_impl__ self.connection = await self.create_connection() File "/usr/local/lib/python3.13/site-packages/websockets/asyncio/client.py", line 467, in create_connection _, connection = await loop.create_connection(factory, **kwargs) File "/usr/local/lib/python3.13/asyncio/base_events.py", line 1187, in create_connection transport, protocol = await self._create_connection_transport( File "/usr/local/lib/python3.13/asyncio/base_events.py", line 1211, in _create_connection_transport transport = self._make_ssl_transport( File "/usr/local/lib/python3.13/asyncio/selector_events.py", line 83, in _make_ssl_transport ssl_protocol = sslproto.SSLProtocol( File "/usr/local/lib/python3.13/asyncio/sslproto.py", line 295, in __init__ sslcontext = _create_transport_context( File "/usr/local/lib/python3.13/asyncio/sslproto.py", line 55, in _create_transport_context sslcontext = ssl.create_default_context() File "/usr/local/lib/python3.13/ssl.py", line 722, in create_default_context context.load_default_certs(purpose) File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func return func(*args, **kwargs) File "/usr/local/lib/python3.13/ssl.py", line 534, in load_default_certs self.set_default_verify_paths()

And this

Logger: homeassistant.setup
Source: setup.py:344
First occurred: 10:05:43 PM (1 occurrence)
Last logged: 10:05:43 PM

Setup failed for custom integration 'govee_lan': Unable to import component: Exception importing custom_components.govee_lan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1053, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1160, in get_code
  File "<frozen importlib._bootstrap_external>", line 1090, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/govee_lan/__init__.py", line 1
    @@ -1,37 +1,33 @@
     ^
SyntaxError: invalid syntax

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 993, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1064, in _get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.govee_lan

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1053, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1160, in get_code
  File "<frozen importlib._bootstrap_external>", line 1090, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/govee_lan/__init__.py", line 1
    @@ -1,37 +1,33 @@
     ^
SyntaxError: invalid syntax

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 344, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1013, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1005, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1064, in _get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.govee_lan

And this

Logger: homeassistant.loader
Source: loader.py:1053
First occurred: 10:05:43 PM (2 occurrences)
Last logged: 10:05:43 PM

Unexpected exception importing component custom_components.govee_lan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1053, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1160, in get_code
  File "<frozen importlib._bootstrap_external>", line 1090, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/govee_lan/__init__.py", line 1
    @@ -1,37 +1,33 @@
     ^
SyntaxError: invalid syntax


Here is a copy of the __init__.py file

@@ -1,37 +1,33 @@
""" Govee LAN Control """
from __future__ import annotations
import voluptuous as vol
import logging
from homeassistant.core import HomeAssistant
from homeassistant.helpers.typing import ConfigType
from homeassistant.config_entries import ConfigEntry
from homeassistant.const import Platform
from .const import DOMAIN
from typing import Dict
from govee_led_wez import GoveeController, GoveeDevice
_LOGGER = logging.getLogger(__name__)
CONFIG_SCHEMA = vol.Schema({vol.Optional(DOMAIN): {}}, extra=vol.ALLOW_EXTRA)
PLATFORMS: list[Platform] = [Platform.LIGHT]
async def async_setup(hass: HomeAssistant, config: ConfigType) -> bool:
    _LOGGER.info("async_setup called!")
    hass.data[DOMAIN] = {}
    return True
async def async_setup_entry(hass: HomeAssistant, entry: ConfigEntry):
    """Set up Govee from a config entry."""
    _LOGGER.info("async_setup_entry called!")

    for component in PLATFORMS:
        hass.async_create_task(
            hass.config_entries.async_forward_entry_setup(entry, component)
        )
    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
    return True


async def async_unload_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool:
    """Unload a config entry."""
    return await hass.config_entries.async_unload_platforms(entry, PLATFORMS)


Any help you can give would be very welcome. 

Thanks!

**Comment by illusian** [comment]
Temporary patch.

Open /homeassistant/custom_components/govee/__init__.py using File editor or so on.

Replace as follows.
From (Line 71  ~ 72)
for component in PLATFORMS:
     await hass.config_entries.async_forward_entry_setup(entry, component)

To
await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)

Saving and restarting HA will work.

**Comment by hdprice** [comment]
> Temporary patch.
> 
> Open /homeassistant/custom_components/govee/**init**.py using File editor or so on.
> 
> Replace as follows. From (Line 71 ~ 72) for component in PLATFORMS: await hass.config_entries.async_forward_entry_setup(entry, component)
> 
> To await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
> 
> Saving and restarting HA will work.

This worked for me! THANK YOU!!!!

**Comment by hartmood** [comment]
> Temporary patch.
> 
> Open /homeassistant/custom_components/govee/**init**.py using File editor or so on.
> 
> Replace as follows. From (Line 71 ~ 72) for component in PLATFORMS: await hass.config_entries.async_forward_entry_setup(entry, component)
> 
> To await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
> 
> Saving and restarting HA will work.

Strange, I just have a folder with name of  "govee_lan" and a file called "__init__.py" (two underscores in front and after the init) and the corresponding section line 31-33:

```
    for component in PLATFORMS:
        hass.async_create_task(
            hass.config_entries.async_forward_entry_setup(entry, component)

```

**Comment by Eric2XU** [comment]
@hdprice I applogize I should have linked the full file. The view you had showed what was to be removed as well as what was to be added. You ended up with both the new and old. 

Here is a direct link to my copy that worked for me and @rustyk123 

https://github.com/wez/govee-lan-hass/blob/c01de8016eb6a3c6a6e36e70dbc333cadb16521f/custom_components/govee_lan/__init__.py

It sounds like you were able to get it work reguardless. I post this for others.

**Comment by hartmood** [comment]
https://github.com/wez/govee-lan-hass/blob/c01de8016eb6a3c6a6e36e70dbc333cadb16521f/custom_components/govee_lan/__init__.py also worked for me. Thanks so much.

**Comment by mihailmoise** [comment]
Thanks! Works for me, also. Broke after HA Core update to 2025.6.0 today.

**Comment by maritzhome1** [comment]
Many thanks for the fix - I am also now sorted.

**Comment by EvanWasHere-zz** [comment]
For any novices like myself that need a little more handholding (took me a few attempts because i kept trying to download the __init__.py link which wasn't working)

1. Make sure you have File Editor and Filebrowser installed on your HA (google instructions on how to install if you don't)
2. Using Filebrowser, go to  homeassistant/custom_components/govee_lan
3. Download the __init__.py file to your computer as a backup.
4. Left click on the Github link above and  once the page loads, click the copy button to grab the code (on the right next to Raw)
5. Using File Editor, go to the same folder I mention in step 2 and edit the __init__.py file on your HA server.
6. Select all the text in that file and paste the new code to replace it.
7. Save the file
8. Restart the server
9. Profit

Hopefully I saved someone 5-10 minutes of sweat as their spouse/family screamed at them that the lights don't work.

Thanks to Eric2XU for the fix!

**Comment by KuruKanagalingam** [comment]
Great it worked for me.

**Comment by erikkampa** [comment]
Thank you to all!  This worked for me.  My wife sometimes thinks I'm crazy for messing with HA and open source, then things like this happens.  I am still learning so all of the advice from Eric2XU and EvanWasHere-zz was incredibly helpful.

**Comment by kosset** [comment]
> I fixed it and submitted a PR
> 
> PR: [#72](https://github.com/wez/govee-lan-hass/pull/72)
> 
> Direct copy of the file for manual replacement: https://github.com/wez/govee-lan-hass/blob/c01de8016eb6a3c6a6e36e70dbc333cadb16521f/custom_components/govee_lan/__init__.py
> 
> He said he’s not updating this repo anymore but at worst take my version of the file and edit your local copy. Since there wont be another update, it shouldn’t get replaced.
> 
> Problem:After upgrading to Home Assistant 2025.5, the integration failed with an error:ModuleNotFoundError: No module named 'custom_components.govee_lan.l'. This was caused by using the outdated async_forward_entry_setup method inside a loop, which led to misinterpreting platform names (e.g., "l" instead of "light").
> 
> Solution:
> 
> Updated API Call: Replaced async_forward_entry_setup with the new async_forward_entry_setups method.
> 
> Simplified Setup: Removed the loop over platforms and now forward all platforms at once:
> 
> await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
> 
> This change aligns the integration with the updated Home Assistant architecture and resolves the module import error.

It worked!! Thank you pal!

**Comment by joreis** [comment]
> I fixed it and submitted a PR
> 
> PR: [#72](https://github.com/wez/govee-lan-hass/pull/72)
> 
> Direct copy of the file for manual replacement: https://github.com/wez/govee-lan-hass/blob/c01de8016eb6a3c6a6e36e70dbc333cadb16521f/custom_components/govee_lan/__init__.py
> 
> He said he’s not updating this repo anymore but at worst take my version of the file and edit your local copy. Since there wont be another update, it shouldn’t get replaced.
> 
> Problem:After upgrading to Home Assistant 2025.5, the integration failed with an error:ModuleNotFoundError: No module named 'custom_components.govee_lan.l'. This was caused by using the outdated async_forward_entry_setup method inside a loop, which led to misinterpreting platform names (e.g., "l" instead of "light").
> 
> Solution:
> 
> Updated API Call: Replaced async_forward_entry_setup with the new async_forward_entry_setups method.
> 
> Simplified Setup: Removed the loop over platforms and now forward all platforms at once:
> 
> await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
> 
> This change aligns the integration with the updated Home Assistant architecture and resolves the module import error.

It worked! Thanks

**Comment by gillesguillemin** [comment]
Nice one, thanks @Eric2XU 👍

**Comment by Chayalut** [comment]
@Eric2XU 
thank you so much. best man.

**Comment by christylerie** [comment]
thank you very much  @Eric2XU

**Comment by Frema180** [comment]
Thank you @Eric2XU for the fix and @EvanWasHere-zz for the how to!

**Comment by MiniFido** [comment]
Tanks works.

**Comment by danioj** [comment]
> > Temporary patch.
> > Open /homeassistant/custom_components/govee/**init**.py using File editor or so on.
> > Replace as follows. From (Line 71 ~ 72) for component in PLATFORMS: await hass.config_entries.async_forward_entry_setup(entry, component)
> > To await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
> > Saving and restarting HA will work.
> 
> Strange, I just have a folder with name of "govee_lan" and a file called "**init**.py" (two underscores in front and after the init) and the corresponding section line 31-33:
> 
> ```
>     for component in PLATFORMS:
>         hass.async_create_task(
>             hass.config_entries.async_forward_entry_setup(entry, component)
> ```

Same situation for me as this user. But just edited the corresponding line same as proposed by the user with a file with 70+ lines and everything is back and working. 

Thank you very much for this fix.

**Comment by Cod053** [comment]
Quick note: 

I found that editing just line 72 in Govee/__init__.py didn't do the trick, because line 33 in govee_lan/__init__.py also had the same issues. 

Editing the lines in both files sorted the issue and a restart got everything working again.

For govee_lan/__init__.py the line to be changed is

hass.config_entries.async_forward_entry_setup(entry, component)

to

hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)

There's no "await" in the line in the lan file.

**Comment by unc2k3** [comment]
> Quick note:
> 
> I found that editing just line 72 in Govee/**init**.py didn't do the trick, because line 33 in govee_lan/**init**.py also had the same issues.
> 
> Editing the lines in both files sorted the issue and a restart got everything working again.
> 
> For govee_lan/**init**.py the line to be changed is
> 
> hass.config_entries.async_forward_entry_setup(entry, component)
> 
> to
> 
> hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
> 
> There's no "await" in the line in the lan file.

Well I have changed the lines in both govee init.py and govee_lan init.py files and it still doesn't work.  Any ideas?

**Comment by williamhoare** [comment]
> I fixed it and submitted a PR
> 
> PR: [#72](https://github.com/wez/govee-lan-hass/pull/72)
> 
> Direct copy of the file for manual replacement: https://github.com/wez/govee-lan-hass/blob/c01de8016eb6a3c6a6e36e70dbc333cadb16521f/custom_components/govee_lan/__init__.py
> 
> He said he’s not updating this repo anymore but at worst take my version of the file and edit your local copy. Since there wont be another update, it shouldn’t get replaced.
> 
> Problem:After upgrading to Home Assistant 2025.5, the integration failed with an error:ModuleNotFoundError: No module named 'custom_components.govee_lan.l'. This was caused by using the outdated async_forward_entry_setup method inside a loop, which led to misinterpreting platform names (e.g., "l" instead of "light").
> 
> Solution:
> 
> Updated API Call: Replaced async_forward_entry_setup with the new async_forward_entry_setups method.
> 
> Simplified Setup: Removed the loop over platforms and now forward all platforms at once:
> 
> await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
> 
> This change aligns the integration with the updated Home Assistant architecture and resolves the module import error.

Works perfectly - Thanks 👍

**Comment by riddle-stc** [comment]
Thank you very much for this fix.

**Comment by steyrblade** [comment]
Thx from my side, too :-)

**Comment by Taiyoukeilabs** [comment]
> I fixed it and submitted a PR
> 
> PR: [#72](https://github.com/wez/govee-lan-hass/pull/72)
> 
> Direct copy of the file for manual replacement: https://github.com/wez/govee-lan-hass/blob/c01de8016eb6a3c6a6e36e70dbc333cadb16521f/custom_components/govee_lan/__init__.py
> 
> He said he’s not updating this repo anymore but at worst take my version of the file and edit your local copy. Since there wont be another update, it shouldn’t get replaced.
> 
> Problem:After upgrading to Home Assistant 2025.5, the integration failed with an error:ModuleNotFoundError: No module named 'custom_components.govee_lan.l'. This was caused by using the outdated async_forward_entry_setup method inside a loop, which led to misinterpreting platform names (e.g., "l" instead of "light").
> 
> Solution:
> 
> Updated API Call: Replaced async_forward_entry_setup with the new async_forward_entry_setups method.
> 
> Simplified Setup: Removed the loop over platforms and now forward all platforms at once:
> 
> await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
> 
> This change aligns the integration with the updated Home Assistant architecture and resolves the module import error.

This worked for me as well. On HA version Core 2025.6.3. Thank you!

**Comment by ZsiNorb** [comment]
Confirmed working on 2025.7.1. Cheers.
